apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: walkthroughs.integreatly.aerogear.org
spec:
  group: integreatly.aerogear.org
  names:
    kind: Walkthrough
    listKind: WalkthroughList
    plural: walkthroughs
    singular: walkthrough
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            namespace:
              type: string
            username:
              type: string
            services:
              type: array
              items:
                type: string
