apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: walkthroughs.integreatly.aerogear.org
spec:
  group: integreatly.aerogear.org
  names:
    kind: Walkthrough
    listKind: WalkthroughList
    plural: walkthroughs
    singular: walkthrough
  scope: Namespaced
  version: v1alpha1
